# run the binary
version: '3.8'
services:
  app:
    container_name: pastebin
    image: "ubuntu:22.04"
    command: "/app/pastebin"
    volumes:
      - ./pastebin:/app/pastebin
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pastebin.entrypoints=web"
      - "traefik.http.routers.pastebin.rule=Host(`pastebin.localhost`)"
      
    expose:
      - 8000
    networks:
      - proxy

networks:
  proxy:
    external: true